### PR TITLE
Update pastebin automatically with newest installer

### PR DESCRIPTION
**Pull request by Math-ias**
I created a small script to remove some of the hassle with pasting a new pastebin code for when the installer changes.

A small revision that really doesn't accomplish any of the goals, but something that is nice to have. :smile:

### CODE REVIEW

**Comment by HugoNikanor** [comment]
Does this create a new paste every time, or does it update the current one?

**Comment by Math-ias** [comment]
It creates a new paste each time, I don't believe the api makes editing pastes possible.

**Comment by HugoNikanor** [comment]
Alright.
I'm not sure how useful this will be, 
But I will merge it if you document the `PASTEBIN_API_KEY` file. (that it should exist, and what it should contain (which I just guess is the api key to pastebin, but it should be written down))

**Comment by Math-ias** [comment]
Haha, yes I only realized after creating `upload.py` that the installer really wouldn't change much and thus this script wouldn't be too useful, and might be overkill. Oh well. It's a nice tool to have nevertheless.

_EDIT_: I've updated the README.md about the key file.

**Pull request merged**
