### PR TITLE
Move files to .lua extension.

### PR DESCRIPTION
**Pull request by Math-ias**
I have not tested this in game and I have not updated the README using the new script. I forgot to update the pastebin code, however it still is to be seen if it works. I would wait for merging until I can validate that this works and these are the intended changes.

Also, gonna reference: #5 

EDIT: Should I attempt to merge into dev or master?

### CODE REVIEW

**Comment by Vexatos** [comment]
Mind that ComputerCraft normally doesn't expect the extension to be there for some reason, so having a file with a `.lua` extension may have certain things not work (e.g. running `vim` won't make the shell search for `vim.lua`, only `vim` and thus have the command fail unless you actually type in `vim.lua`). Be careful.

**Comment by Math-ias** [comment]
I've used `string.sub(1, -4)` to sub out the .lua extension in the lua installer.

**Comment by HugoNikanor** [comment]
I might have done something weird with the branches. 
(like trying to delete the 'dev' branch)

I'm currently working on merging this pull request into master. Hopefully all will go as planed.

**Comment by HugoNikanor** [comment]
There! I might have created a big mess with git. But I did my best with it.

**Pull request closed without merging**
